### PR TITLE
Generate a universal wheel in addition to the source distribution

### LINKED ISSUE #7: Provide wheel distribution on PyPI
Hi!

Please could this package also by made available as a wheel on PyPI?
https://pypi.python.org/pypi/itypes/1.1.0

Wheels have the following advantages:
* Faster installation time
* Allows the wheel cache to work even when using the new pip hash-checking mode
* Allows tools to statically inspect the package metadata without having to execute untrusted code.
* ...and more - see: http://pythonwheels.com

It's not clear if this package also supports Python 3 (#6), but if so it can be distributed as a "universal wheel":
https://packaging.python.org/tutorials/distributing-packages/#wheels

To save having to pass `--universal` to `setup.py` each time, the pref can be saved in `setup.cfg`:

```
[bdist_wheel]
universal=1
```

If only Python 2 is supported, then skip the above.

The Python packaging guide recommends using [Twine](https://github.com/pypa/twine) to upload packages:
https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi

So with the `setup.cfg` as above, the steps for building/uploading a new release are then:

```bash
$ pip install -U twine setuptools wheel
$ rm -rf dist/ build/
$ python setup.py sdist bdist_wheel
$ twine upload dist/*
```

The PyPI package listing will then display two entries for the new release, one with type "Source" and the other "Python Wheel".

Many thanks :-)

### PR DESCRIPTION
**Pull request by edmorley**
Fixes #7.

### CODE REVIEW

**Comment by tomchristie** [comment]
Yup looks good. Apparently some unrelated issues around pulling in the `.travis.yml` changes (restarting the build didn't resolve this, oddly).
I'll defer pulling this in until rolling a release.

**Comment by edmorley** [comment]
The master at the time the PR was opened didn't include #8, so didn't have a `.travis.yml`. Now that #8 has merged, I've rebased.

**Comment by edmorley** [comment]
@tomchristie, due to the maturity of this package, I'm presuming the next feature/bug release of this package might be a way out. As such, would you be open to merging this and just uploading the wheel for the existing version?

**Comment by edmorley** [comment]
@tomchristie don't suppose you saw this? :-)

> As such, would you be open to merging this and just uploading the wheel for the existing version?

**Pull request closed without merging**
